version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  deploy:
    steps:
      - checkout
      - run:
          name: deploy prowler
          command: 'make deploy'

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
